spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: ${ENABLE_SECOND_LEVEL_CACHE:true}
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
    hibernate:
      ddl-auto: update



grpc:
  server:
    port: 6565
    isReflectionServiceEnabled: true